import { IDay } from "./Days";

export const week: IDay[] = [
  {
    dayName: "Сегодня",
    day_info: "28 авг",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Солнечно",
  },
  {
    dayName: "Завтра",
    day_info: "29 авг",
    icon_id: "sun_small_clouds",
    temp_day: "+15",
    temp_night: "+10",
    info: "Облачно",
  },
  {
    dayName: "Пн",
    day_info: "30 авг",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Небольшой дождь",
  },
  {
    dayName: "Вт",
    day_info: "31 авг",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Ср",
    day_info: "1 сент",
    icon_id: "sun_small_clouds",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Чт",
    day_info: "2 сент",
    icon_id: "cloudy",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Пт",
    day_info: "3 сент",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
];

export const tenDays: IDay[] = [
  {
    dayName: "Сегодня",
    day_info: "28 авг",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Завтра",
    day_info: "29 авг",
    icon_id: "sun_small_clouds",
    temp_day: "+15",
    temp_night: "+10",
    info: "Небольшой дождь",
  },
  {
    dayName: "Пн",
    day_info: "30 авг",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Вт",
    day_info: "31 авг",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Ср",
    day_info: "1 сент",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Чт",
    day_info: "2 сент",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Пт",
    day_info: "3 сент",
    icon_id: "sun_small_clouds",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Пт",
    day_info: "3 сент",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Сб",
    day_info: "4 сент",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "Вс",
    day_info: "5 сент",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    dayName: "пн",
    day_info: "6 сент",
    icon_id: "sun_small_clouds",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
];



